---
title: "McKenna Analysis - Percentile and Basic "
author: "McKenna Hogan"
date: '2022-11-17'
output: pdf_document
---

```{r libraries}
library(tidyverse)
library(knitr)
library(dplyr)
library(simpleboot)
library(boot) 
```

```{r data}
#skewed data
diab.data1<- read_csv("~/STAT400/Project 1/data/diabetes_012_health_indicators_BRFSS2015.csv")
#unskewed data
diab.data2<- 
  read_csv("~/STAT400/Project 1/data/diabetes_binary_5050split_health_indicators_BRFSS2015.csv")
diab.data3<- read_csv("~/STAT400/Project 1/data/diabetes_binary_health_indicators_BRFSS2015.csv")

nodiab.only.1<-diab.data1|>
  filter(Diabetes_012==0)|>
  select(HighBP,HighChol,BMI,AnyHealthcare,GenHlth,Income)
prediab.only.1<-diab.data1|>
  filter(Diabetes_012==1)|>
  select(HighBP,HighChol,BMI,AnyHealthcare,GenHlth,Income)
diab.only.1<-diab.data1|>
  filter(Diabetes_012==2)|>
  select(HighBP,HighChol,BMI,AnyHealthcare,GenHlth,Income)
```





```{r new function data}

HighBP0<-nodiab.only.1$HighBP
HighBP1<-prediab.only.1$HighBP
HighBP2<-diab.only.1$HighBP

HighChol0<-nodiab.only.1$HighChol
HighChol1<-prediab.only.1$HighChol
HighChol2<-diab.only.1$HighChol

BMI0<-nodiab.only.1$BMI
BMI1<-prediab.only.1$BMI
BMI2<-diab.only.1$BMI

AnyHealthcare0<-nodiab.only.1$AnyHealthcare
AnyHealthcare1<-prediab.only.1$AnyHealthcare
AnyHealthcare2<-diab.only.1$AnyHealthcare

GenHlth0<-nodiab.only.1$GenHlth
GenHlth1<-prediab.only.1$GenHlth
GenHlth2<-diab.only.1$GenHlth

Income0<-nodiab.only.1$Income
Income1<-prediab.only.1$Income
Income2<-diab.only.1$Income

```


```{r}
#just bp
  no_pre<- two.boot(HighBP0, HighBP1, "mean", R = 50)

  boot.no_pre<-boot.ci(no_pre,type=c("perc","basic"))
  
  plot.no_pre<-ggplot() +
    geom_histogram(aes(no_pre$t))+
    geom_segment(aes(y=25,yend=25,x=boot.no_pre$percent[4],
                     xend=boot.no_pre$percent[5], col="percentile"))+
    geom_segment(aes(y=35,yend=35,x=boot.no_pre$basic[4],
                     xend=boot.no_pre$basic[5],col="basic"))+
    xlab("mean(no diabetes) - mean(prediabetes)")


  
  se.no_pre<-sd(no_pre$t)

  
  bias.no_pre<-rep(NA,500)

  for (i in 1:500){
    bias.no_pre[i]<-no_pre$t[i]-no_pre$t0

  }
  # bias.no_pre<-mean(bias.no_pre)+
  #   geom_error_barh(aes(y=20,xmin=boot.no_pre))

  
  
  
plot.no_pre

```

```{r}
diff.means<-function(data0,data1,data2,R){
  
  
  no_pre<- two.boot(data0, data1, "mean", R = R)
  pre_diab<- two.boot(data1, data2, "mean", R = R)
  diab_no<- two.boot(data2, data0, "mean", R = R)
  
  se.no_pre<-sd(no_pre$t)
  se.pre_diab<-sd(pre_diab$t)
  se.diab_no<-sd(diab_no$t)
  
  bias.no_pre<-rep(NA,R)
  bias.pre_diab<-rep(NA,R)
  bias.diab_no<-rep(NA,R)
  for (i in 1:R){
    bias.no_pre[i]<-no_pre$t[i]-no_pre$t0
    bias.pre_diab[i]<-pre_diab$t[i]-pre_diab$t0
    bias.diab_no[i]<-diab_no$t[i]-diab_no$t0
  }
  bias.no_pre<-mean(bias.no_pre)
  bias.pre_diab<-mean(bias.pre_diab)
  bias.diab_no<-mean(bias.diab_no)
  
  boot.no_pre<-boot.ci(no_pre,type=c("perc","basic"))
  boot.pre_diab<-boot.ci(pre_diab,type=c("perc","basic"))
  boot.diab_no<-boot.ci(diab_no,type=c("perc","basic"))
  
  plot.no_pre<-ggplot() +
    geom_histogram(aes(no_pre$t, fill="darkgoldenrod1")) +
    geom_segment(aes(y=25,yend=25,x=boot.no_pre$percentile[4],
                     xend=boot.no_pre$percentile[5], col="percentile"))+
    geom_segment(aes(y=35,yend=35,x=boot.no_pre$basic[4],
                     xend=boot.no_pre$basic[5],col="basic"))+
    xlab("mean(no diabetes) - mean(prediabetes)")
  
  plot.pre_diab<-ggplot() +
    geom_histogram(aes(pre_diab$t),fill="deepskyblue") +
    xlab("mean(pre diabetes) - mean(diabetes)")
  plot.diab_no<-ggplot() +
    geom_histogram(aes(diab_no$t),fill="coral") +
    xlab("mean(diabetes) - mean(no prediabetes)")

  return(list(plot.no_pre, se.no_pre, bias.no_pre, boot.no_pre,
              plot.pre_diab, se.pre_diab, bias.pre_diab, boot.pre_diab,
              plot.diab_no, se.diab_no, bias.diab_no, boot.diab_no))
}

```

```{r}
HighBP.list<-diff.means.percentile(HighBP0,HighBP1,HighBP2,1000)
HighBP.list[1]
#HighChol.list<-diff.means.percentile(HighChol0,HighChol1,HighChol2,1000)
#BMI.list<-diff.means.percentile(BMI0,BMI1,BMI2,1000)
#AnyHealthcare.list<-diff.means.percentile(AnyHealthcare0,AnyHealthcare1,AnyHealthcare2,1000)
#GenHlth.list<-diff.means.percentile(GenHlth0,GenHlth1,GenHlth2,1000)
#Income.list<-diff.means.percentile(Income0,Income1,Income2,1000)

```







I did not use any of the following functions:
```{r percentile bootstrap func}
#income, bmi, genhealth, bp, anyhealthcare
#pull size n, m times
percentile_basic_bootstrap1<-function(data,m,n){
  mean.HighBP<-numeric(m)
  mean.HighChol<-numeric(m)
  mean.BMI<-numeric(m)
  mean.AnyHealthcare<-numeric(m)
  mean.GenHlth<-numeric(m)
  mean.Income<-numeric(m)
  
  pCI.HighBP.low<-numeric(m)
  pCI.HighBP.high<-numeric(m)
  pCI.HighChol.low<-numeric(m)
  pCI.HighChol.high<-numeric(m)
  pCI.BMI.low<-numeric(m)
  pCI.BMI.high<-numeric(m)
  pCI.AnyHealthcare.low<-numeric(m)
  pCI.AnyHealthcare.high<-numeric(m)
  pCI.GenHlth.low<-numeric(m)
  pCI.GenHlth.high<-numeric(m)
  pCI.Income.low<-numeric(m)
  pCI.Income.high<-numeric(m)
  
  bCI.HighBP.low<-numeric(m)
  bCI.HighBP.high<-numeric(m)
  bCI.HighChol.low<-numeric(m)
  bCI.HighChol.high<-numeric(m)
  bCI.BMI.low<-numeric(m)
  bCI.BMI.high<-numeric(m)
  bCI.AnyHealthcare.low<-numeric(m)
  bCI.AnyHealthcare.high<-numeric(m)
  bCI.GenHlth.low<-numeric(m)
  bCI.GenHlth.high<-numeric(m)
  bCI.Income.low<-numeric(m)
  bCI.Income.high<-numeric(m)
  
  for (b in seq_len(m)){
    which.col<-sample(seq_len(n),n,replace=T)
    bootstrap.reps<-data[which.col,]
  
    #means
    mean.HighBP[b]<-mean(bootstrap.reps$HighBP)
    mean.HighChol[b]<-mean(bootstrap.reps$HighChol)
    mean.BMI[b]<-mean(bootstrap.reps$BMI)
    mean.AnyHealthcare[b]<-mean(bootstrap.reps$AnyHealthcare)
    mean.GenHlth[b]<-mean(bootstrap.reps$GenHlth)
    mean.Income[b]<-mean(bootstrap.reps$Income)
    
    #percentile
    pCI.HighBP.low[b]<-mean.HighBP[b]-1.96*sqrt((mean.HighBP[b]*(1-mean.HighBP[b]))/n)
    pCI.HighBP.high[b]<-mean.HighBP[b]+1.96*sqrt((mean.HighBP[b]*(1-mean.HighBP[b]))/n)
    pCI.HighChol.low[b]<-mean.HighBP[b]-1.96*sqrt((mean.HighChol[b]*(1-mean.HighChol[b]))/n)
    pCI.HighChol.high[b]<-mean.HighBP[b]+1.96*sqrt((mean.HighChol[b]*(1-mean.HighChol[b]))/n)
    pCI.BMI.low[b]<-quantile(bootstrap.reps$BMI,.025)
    pCI.BMI.high[b]<-quantile(bootstrap.reps$BMI,.975)
    pCI.AnyHealthcare.low[b]<-mean.AnyHealthcare[b]-
                            1.96*sqrt((mean.AnyHealthcare[b]*(1-mean.AnyHealthcare[b]))/n)
    pCI.AnyHealthcare.high[b]<-mean.AnyHealthcare[b]+
                            1.96*sqrt((mean.AnyHealthcare[b]*(1-mean.AnyHealthcare[b]))/n)
    pCI.GenHlth.low[b]<-quantile(bootstrap.reps$GenHlth,.025)
    pCI.GenHlth.high[b]<-quantile(bootstrap.reps$GenHlth,.975)
    pCI.Income.low[b]<-quantile(bootstrap.reps$Income,.025)
    pCI.Income.high[b]<-quantile(bootstrap.reps$Income,.975)
    
    #basic
    bCI.HighBP.low[b]<-2*mean.HighBP[b]-quantile(bootstrap.reps$HighBP,.975)
    bCI.HighBP.high[b]<-2*mean.HighBP[b]-quantile(bootstrap.reps$HighBP,.025)
    bCI.HighChol.low[b]<-2*mean.HighChol[b]-quantile(bootstrap.reps$HighChol,.975)
    bCI.HighChol.high[b]<-2*mean.HighChol[b]-quantile(bootstrap.reps$HighChol,.025)
    bCI.BMI.low[b]<-2*mean.BMI[b]-quantile(bootstrap.reps$BMI,.975)
    bCI.BMI.high[b]<-2*mean.BMI[b]-quantile(bootstrap.reps$BMI,.025)
    bCI.AnyHealthcare.low[b]<-
      2*mean.AnyHealthcare[b]-quantile(bootstrap.reps$AnyHealthcare,.975)
    bCI.AnyHealthcare.high[b]<-
      2*mean.AnyHealthcare[b]-quantile(bootstrap.reps$AnyHealthcare,.025)
    bCI.GenHlth.low[b]<-2*mean.GenHlth[b]-quantile(bootstrap.reps$GenHlth,.975)
    bCI.GenHlth.high[b]<-2*mean.GenHlth[b]-quantile(bootstrap.reps$GenHlth,.025)
    bCI.Income.low[b]<-2*mean.Income[b]-quantile(bootstrap.reps$Income,.975)
    bCI.Income.high[b]<-2*mean.Income[b]-quantile(bootstrap.reps$Income,.025)
  
  }
  #tables
  mean.table<-data.frame(cbind(mean.HighBP,mean.HighChol,mean.BMI,
                         mean.AnyHealthcare,mean.GenHlth,mean.Income))
  colnames(mean.table)<-c("High BP","High Chol","BMI",
                          "Any Healthcare","General Health","Income")

  pCI.table<-data.frame(cbind(pCI.HighBP.low,pCI.HighBP.high,
                   pCI.HighChol.low,pCI.HighChol.high,
                   pCI.BMI.low,pCI.BMI.high,
                   pCI.AnyHealthcare.low,pCI.AnyHealthcare.high,
                   pCI.GenHlth.low,pCI.GenHlth.high,
                   pCI.Income.low,pCI.Income.high))
  colnames(pCI.table)<-c(".025 High BP",".975 High BP",".025 High Chol",".975 High Chol",
                         ".025 BMI",".975 BMI",".025 Healthcare",".975 Healthcare",
                         ".025 General Health",".975 General health",
                         ".025 income",".975 income")
  bCI.table<-data.frame(cbind(bCI.HighBP.low,bCI.HighBP.high,
                   bCI.HighChol.low,bCI.HighChol.high,
                   bCI.BMI.low,bCI.BMI.high,
                   bCI.AnyHealthcare.low,bCI.AnyHealthcare.high,
                   bCI.GenHlth.low,bCI.GenHlth.high,
                   bCI.Income.low,bCI.Income.high))
  colnames(bCI.table)<-c(".025 High BP",".975 High BP",".025 High Chol",".975 High Chol",
                         ".025 BMI",".975 BMI",".025 Healthcare",".975 Healthcare",
                         ".025 General Health",".975 General health",
                         ".025 income",".975 income")
  kable_mean.table<-kable(mean.table,digits=3,align="c", caption ="means")
  kable_pCI.table<-kable(pCI.table,digits=3,align="c", caption = "percentile CI")
  kable_bCI.table<-kable(bCI.table,digits=3,align="c", caption = "basic CI")
  
  #graphs
  
  variables<-c("High BP","High Chol","BMI",
                        "Any Healthcare","General Health","Income")
  graph.data<-data.frame(cbind(variables,rbind(as.numeric(mean.HighBP),
                                               as.numeric(mean.HighChol),
                                               as.numeric(mean.BMI),
                                               as.numeric(mean.AnyHealthcare),
                                               as.numeric(mean.GenHlth),
                                               as.numeric(mean.Income))))
  colnames(graph.data)<-c("variable",seq(from=1,to=m,by=1))


  mean.graphs<-ggplot(graph.data)+
    geom_histogram()+
    facet_wrap(~variable)

  
  # mean.graphs<-ggplot(mean.table)+
  #   geom_histogram()+
  #   facet_wrap(variables)
  
  
  
  
  
  
  return(list(kable_mean.table,kable_pCI.table,kable_bCI.table,graph.data))
}
percentile_basic_bootstrap1(nodiab.only.1,5,10)


```

```{r percentile bootstrap func}
#income, bmi, genhealth, bp, anyhealthcare
#pull size n, m times
percentile_basic_bootstrap<-function(data,m,n){
  for (b in seq_len(m)){
    which.col<-sample(seq_len(n),n,replace=T)
    bootstrap.reps<-data[which.col,]
  }
  #means
  mean.HighBP<-mean(bootstrap.reps$HighBP)
  mean.HighChol<-mean(bootstrap.reps$HighChol)
  mean.BMI<-mean(bootstrap.reps$BMI)
  mean.AnyHealthcare<-mean(bootstrap.reps$AnyHealthcare)
  mean.GenHlth<-mean(bootstrap.reps$GenHlth)
  mean.Income<-mean(bootstrap.reps$Income)
  mean.table<-data.frame(mean.HighBP,mean.HighChol,
                         mean.BMI,mean.AnyHealthcare,mean.GenHlth,mean.Income)
  rownames(mean.table)<-c("mean")
  colnames(mean.table)<-c("High BP","High Chol",
                          "BMI","Any Healthcare","General Health","Income")
  mean.kable<-kable(mean.table,align="c",caption="means",digits=2)
  means<-c(mean.HighBP,mean.HighChol,
                         mean.BMI,mean.AnyHealthcare,mean.GenHlth,mean.Income)
  
  #percentile CI's
  p.CI.HighBP<-c(mean.HighBP-1.96*sqrt((mean.HighBP*(1-mean.HighBP))/n),
                   mean.HighBP+1.96*sqrt((mean.HighBP*(1-mean.HighBP))/n))
  p.CI.HighChol<-c(mean.HighChol-1.96*sqrt((mean.HighChol*(1-mean.HighChol))/n),
                   mean.HighChol+1.96*sqrt((mean.HighChol*(1-mean.HighChol))/n))
  p.CI.BMI<-quantile(bootstrap.reps$BMI,c(.025,.975))
  p.CI.AnyHealthcare<-c(mean.AnyHealthcare-
                          1.96*sqrt((mean.AnyHealthcare*(1-mean.AnyHealthcare))/n),
                   mean.AnyHealthcare+1.96*sqrt((mean.AnyHealthcare*(1-mean.AnyHealthcare))/n))
  p.CI.GenHlth<-quantile(bootstrap.reps$GenHlth,c(.025,.975))
  p.CI.Income<-quantile(bootstrap.reps$Income,c(.025,.975))
  p.CI.table<-data.frame(p.CI.HighBP,p.CI.HighChol,
                         p.CI.BMI,p.CI.AnyHealthcare,p.CI.GenHlth,p.CI.Income)
  colnames(p.CI.table)<-c("High BP","High Chol",
                        "BMI","Any Healthcare","General Health","Income")
  p.CI.kable<-kable(p.CI.table,align="c",caption="percentile CI",digits=2)
  p.CIs<-c(p.CI.HighBP,p.CI.HighChol,
                         p.CI.BMI,p.CI.AnyHealthcare,p.CI.GenHlth,p.CI.Income)
  
  #basic CI's
  b.CI.HighBP<-c(2*mean.HighBP-quantile(bootstrap.reps$HighBP,.975),
                 2*mean.HighBP-quantile(bootstrap.reps$HighBP,.025))
  b.CI.HighChol<-c(2*mean.HighChol-quantile(bootstrap.reps$HighChol,.975),
                 2*mean.HighChol-quantile(bootstrap.reps$HighChol,.025))
  b.CI.BMI<-c(2*mean.BMI-quantile(bootstrap.reps$BMI,.975),
                 2*mean.BMI-quantile(bootstrap.reps$BMI,.025))
  b.CI.AnyHealthcare<-c(2*mean.AnyHealthcare-quantile(bootstrap.reps$AnyHealthcare,.975),
                 2*mean.AnyHealthcare-quantile(bootstrap.reps$AnyHealthcare,.025))
  b.CI.GenHlth<-c(2*mean.GenHlth-quantile(bootstrap.reps$GenHlth,.975),
                 2*mean.GenHlth-quantile(bootstrap.reps$GenHlth,.025))
  b.CI.Income<-c(2*mean.Income-quantile(bootstrap.reps$Income,.975),
                 2*mean.Income-quantile(bootstrap.reps$Income,.025))
  b.CI.table<-data.frame(b.CI.HighBP,b.CI.HighChol,
                         b.CI.BMI,b.CI.AnyHealthcare,b.CI.GenHlth,b.CI.Income)
  colnames(b.CI.table)<-c("High BP","High Chol",
                        "BMI","Any Healthcare","General Health","Income")
  b.CI.kable<-kable(b.CI.table,align="c",caption="basic CI",digits=2)

  all.table<-rbind(mean.table,p.CI.table,b.CI.table)
  rownames(all.table)<-c("mean",".025 percentile",".975 percentile",".025 basic",".975 basic")
  kable.alltable<-kable(all.table,digits=2,align="c")
  return(list(bootstrap.reps,kable.alltable))
}
```

```{r old code}
#income, bmi, genhealth, bp, anyhealthcare

# set up the bootstrap
# B <- 1000
# n <- nrow(law)
# theta_hat_star <- numeric(B) # storage
# 
# for(b in seq_len(B)) {
#   ## Your Turn: Do the bootstrap!
#   #get bootstrap dataset
#   idx_star<-sample(seq_len(n),n,replace = T)
#   x_star<-law[idx_star,]
#   
#   #computing teh statistic
#   theta_hat_star[b]<-cor(x_star$lsat,x_star$gpa)
# }
#pull size n, m times
percentile_bootstrap<-function(data,n,m){
  for (b in seq_len(m)){
    which.col<-sample(seq_len(n),n,replace=T)
    bootstrap.reps<-data[which.col,]
  }
  mean.HighBP<-rep(NA,m)
  mean.HighChol<-rep(NA,m)
  mean.BMI<-rep(NA,m)
  mean.AnyHealthcare<-rep(NA,m)
  mean.GenHlth<-rep(NA,m)
  mean.Income<-rep(NA,m)
  for(i in 1:m){
    start_i<-n*(i-1)+1
    end_i<-n*i
    mean.HighBP<-mean(bootstrap.reps$HighBP[start_i:end_i])
    mean.HighChol<-mean(bootstrap.reps$HighChol[start_i:end_i])
    mean.BMI<-mean(bootstrap.reps$BMI[start_i:end_i])
    mean.AnyHealthcare<-mean(bootstrap.reps$AnyHealthcare[start_i:end_i])
    mean.GenHlth<-mean(bootstrap.reps$GenHlth[start_i:end_i])
    mean.Income<-mean(bootstrap.reps$Income[start_i:end_i])
  }
  mean.table<-data.frame(mean.HighBP,mean.HighChol,
                         mean.BMI,mean.AnyHealthcare,mean.GenHlth,mean.Income)
  mean.kable<-kable(mean.table)
  # CI.HighBP<-rep(NA,m)
  # CI.HighChol<-rep(NA,m)
  # CI.BMI<-rep(NA,m)
  # CI.AnyHealthcare<-rep(NA,m)
  # CI.GenHlth<-rep(NA,m)
  # CI.Income<-rep(NA,m)
  # for(i in 1:m){
  #   start_i<-n*(i-1)+1
  #   end_i<-n*i
  #   CI.HighBP<-quantile(bootstrap.reps$HighBP[start_i:end_i],c(.025,.975))
  #   CI.HighChol<-quantile(bootstrap.reps$HighChol[start_i:end_i],c(.025,.975))
  #   CI.BMI<-quantile(bootstrap.reps$BMI[start_i:end_i],c(.025,.975))
  #   CI.AnyHealthcare<-quantile(bootstrap.reps$AnyHealthcare[start_i:end_i],c(.025,.975))
  #   CI.GenHlth<-quantile(bootstrap.reps$GenHlth[start_i:end_i],c(.025,.975))
  #   CI.Income<-quantile(bootstrap.reps$Income[start_i:end_i],c(.025,.975))
  # }
  # 
  return(list(bootstrap.reps,mean.kable))
}

```

```{r BCa}
diff.means.BCa<-function(data0,data1,data2,R){
  
  
  no_pre<- two.boot(data0, data1, "mean", R = R)
  pre_diab<- two.boot(data1, data2, "mean", R = R)
  diab_no<- two.boot(data2, data0, "mean", R = R)
  
  plot.no_pre<-ggplot() +
    geom_histogram(aes(no_pre$t), fill="darkgoldenrod1") +
    xlab("mean(no diabetes) - mean(prediabetes)")
  plot.pre_diab<-ggplot() +
    geom_histogram(aes(pre_diab$t),fill="deepskyblue") +
    xlab("mean(pre diabetes) - mean(diabetes)")
  plot.diab_no<-ggplot() +
    geom_histogram(aes(diab_no$t),fill="coral") +
    xlab("mean(diabetes) - mean(no prediabetes)")

  
  se.no_pre<-sd(no_pre$t)
  se.pre_diab<-sd(pre_diab$t)
  se.diab_no<-sd(diab_no$t)
  
  bias.no_pre<-rep(NA,R)
  bias.pre_diab<-rep(NA,R)
  bias.diab_no<-rep(NA,R)
  for (i in 1:R){
    bias.no_pre[i]<-no_pre$t[i]-no_pre$t0
    bias.pre_diab[i]<-pre_diab$t[i]-pre_diab$t0
    bias.diab_no[i]<-diab_no$t[i]-diab_no$t0
  }
  bias.no_pre<-mean(bias.no_pre)
  bias.pre_diab<-mean(bias.pre_diab)
  bias.diab_no<-mean(bias.diab_no)
  
  boot.no_pre<-boot.ci(no_pre,type="bca")
  boot.pre_diab<-boot.ci(pre_diab,type="bca")
  boot.diab_no<-boot.ci(diab_no,type="bca")

  return(list(plot.no_pre, se.no_pre, bias.no_pre, boot.no_pre,
              plot.pre_diab, se.pre_diab, bias.pre_diab, boot.pre_diab,
              plot.diab_no, se.diab_no, bias.diab_no, boot.diab_no))
}

diff.means.BCa(HighBP0,HighBP1,HighBP2,1000)

```

```{r returning bootstrap data}
# m=5 samples
no.percentile.m5.n10<-percentile_basic_bootstrap(nodiab.only.1,5,10)
no.percentile.m5.n25<-percentile_basic_bootstrap(nodiab.only.1,5,25)
no.percentile.m5.n75<-percentile_basic_bootstrap(nodiab.only.1,5,75)
no.percentile.m5.n125<-percentile_basic_bootstrap(nodiab.only.1,5,125)
no.percentile.m5.n250<-percentile_basic_bootstrap(nodiab.only.1,5,250)

pre.percentile.m5.n10<-percentile_basic_bootstrap(prediab.only.1,5,10)
pre.percentile.m5.n25<-percentile_basic_bootstrap(prediab.only.1,5,25)
pre.percentile.m5.n75<-percentile_basic_bootstrap(prediab.only.1,5,75)
pre.percentile.m5.n125<-percentile_basic_bootstrap(prediab.only.1,5,125)
pre.percentile.m5.n250<-percentile_basic_bootstrap(prediab.only.1,5,250)

percentile.m5.n10<-percentile_basic_bootstrap(diab.only.1,5,10)
percentile.m5.n25<-percentile_basic_bootstrap(diab.only.1,5,25)
percentile.m5.n75<-percentile_basic_bootstrap(diab.only.1,5,75)
percentile.m5.n125<-percentile_basic_bootstrap(diab.only.1,5,125)
percentile.m5.n250<-percentile_basic_bootstrap(diab.only.1,5,250)

# m=10 samples
no.percentile.m10.n10<-percentile_basic_bootstrap(nodiab.only.1,10,10)
no.percentile.m10.n25<-percentile_basic_bootstrap(nodiab.only.1,10,25)
no.percentile.m10.n75<-percentile_basic_bootstrap(nodiab.only.1,10,75)
no.percentile.m10.n125<-percentile_basic_bootstrap(nodiab.only.1,10,125)
no.percentile.m10.n250<-percentile_basic_bootstrap(nodiab.only.1,10,250)

pre.percentile.m10.n10<-percentile_basic_bootstrap(prediab.only.1,10,10)
pre.percentile.m10.n25<-percentile_basic_bootstrap(prediab.only.1,10,25)
pre.percentile.m10.n75<-percentile_basic_bootstrap(prediab.only.1,10,75)
pre.percentile.m10.n125<-percentile_basic_bootstrap(prediab.only.1,10,125)
pre.percentile.m10.n250<-percentile_basic_bootstrap(prediab.only.1,10,250)

percentile.m10.n10<-percentile_basic_bootstrap(diab.only.1,10,10)
percentile.m10.n25<-percentile_basic_bootstrap(diab.only.1,10,25)
percentile.m10.n75<-percentile_basic_bootstrap(diab.only.1,10,75)
percentile.m10.n125<-percentile_basic_bootstrap(diab.only.1,10,125)
percentile.m10.n250<-percentile_basic_bootstrap(diab.only.1,10,250)

#m=15 samples
no.percentile.m15.n10<-percentile_basic_bootstrap(nodiab.only.1,15,10)
no.percentile.m15.n25<-percentile_basic_bootstrap(nodiab.only.1,15,25)
no.percentile.m15.n75<-percentile_basic_bootstrap(nodiab.only.1,15,75)
no.percentile.m15.n125<-percentile_basic_bootstrap(nodiab.only.1,15,125)
no.percentile.m15.n250<-percentile_basic_bootstrap(nodiab.only.1,15,250)

pre.percentile.m15.n10<-percentile_basic_bootstrap(prediab.only.1,15,10)
pre.percentile.m15.n25<-percentile_basic_bootstrap(prediab.only.1,15,25)
pre.percentile.m15.n75<-percentile_basic_bootstrap(prediab.only.1,15,75)
pre.percentile.m15.n125<-percentile_basic_bootstrap(prediab.only.1,15,125)
pre.percentile.m15.n250<-percentile_basic_bootstrap(prediab.only.1,15,250)

percentile.m15.n10<-percentile_basic_bootstrap(diab.only.1,15,10)
percentile.m15.n25<-percentile_basic_bootstrap(diab.only.1,15,25)
percentile.m15.n75<-percentile_basic_bootstrap(diab.only.1,15,75)
percentile.m15.n125<-percentile_basic_bootstrap(diab.only.1,15,125)
percentile.m15.n250<-percentile_basic_bootstrap(diab.only.1,15,250)

#m=30 samples
no.percentile.m30.n10<-percentile_basic_bootstrap(nodiab.only.1,30,10)
no.percentile.m30.n25<-percentile_basic_bootstrap(nodiab.only.1,30,25)
no.percentile.m30.n75<-percentile_basic_bootstrap(nodiab.only.1,30,75)
no.percentile.m30.n125<-percentile_basic_bootstrap(nodiab.only.1,30,125)
no.percentile.m30.n250<-percentile_basic_bootstrap(nodiab.only.1,30,250)

pre.percentile.m30.n10<-percentile_basic_bootstrap(prediab.only.1,30,10)
pre.percentile.m30.n25<-percentile_basic_bootstrap(prediab.only.1,30,25)
pre.percentile.m30.n75<-percentile_basic_bootstrap(prediab.only.1,30,75)
pre.percentile.m30.n125<-percentile_basic_bootstrap(prediab.only.1,30,125)
pre.percentile.m30.n250<-percentile_basic_bootstrap(prediab.only.1,30,250)

percentile.m30.n10<-percentile_basic_bootstrap(diab.only.1,30,10)
percentile.m30.n25<-percentile_basic_bootstrap(diab.only.1,30,25)
percentile.m30.n75<-percentile_basic_bootstrap(diab.only.1,30,75)
percentile.m30.n125<-percentile_basic_bootstrap(diab.only.1,30,125)
percentile.m30.n250<-percentile_basic_bootstrap(diab.only.1,30,250)

#m=50 samples
no.percentile.m50.n10<-percentile_basic_bootstrap(nodiab.only.1,50,10)
no.percentile.m50.n25<-percentile_basic_bootstrap(nodiab.only.1,50,25)
no.percentile.m50.n75<-percentile_basic_bootstrap(nodiab.only.1,50,75)
no.percentile.m50.n125<-percentile_basic_bootstrap(nodiab.only.1,50,125)
no.percentile.m50.n250<-percentile_basic_bootstrap(nodiab.only.1,50,250)

pre.percentile.m50.n10<-percentile_basic_bootstrap(prediab.only.1,50,10)
pre.percentile.m50.n25<-percentile_basic_bootstrap(prediab.only.1,50,25)
pre.percentile.m50.n75<-percentile_basic_bootstrap(prediab.only.1,50,75)
pre.percentile.m50.n125<-percentile_basic_bootstrap(prediab.only.1,50,125)
pre.percentile.m50.n250<-percentile_basic_bootstrap(prediab.only.1,50,250)

percentile.m50.n10<-percentile_basic_bootstrap(diab.only.1,50,10)
percentile.m50.n25<-percentile_basic_bootstrap(diab.only.1,50,25)
percentile.m50.n75<-percentile_basic_bootstrap(diab.only.1,50,75)
percentile.m50.n125<-percentile_basic_bootstrap(diab.only.1,50,125)
percentile.m50.n250<-percentile_basic_bootstrap(diab.only.1,50,250)

```